image: node:8.10.0

cache:
  paths:
  - node_modules/

stages:
- production

# Deploy to staging
Production:
  image: ruby:latest
  only:
  - master
  stage: production
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=getir-todo-backend --api-key=$HEROKU_API_KEY